// Routes
export { default as MainPage } from '../pages/MainPage'
export { default as DashboardPage } from '../pages/DashboardPage'
export { default as ActivatePage } from '../pages/ActivatePage'
export { default as SearchPage } from '../pages/SearchPage'
export { default as NotificationsPage } from '../pages/NotificationsPage'
export { default as OrdersPage } from '../pages/OrdersPage'
export { default as OrdersReturnsPage } from '../pages/OrdersReturnsPage'
export { default as MailPage } from '../pages/MailPage'
export { default as ProfileSettingsPage } from '../pages/ProfileSettingsPage'
export { default as PaymentsPage } from '../pages/PaymentsPage'
export { default as AccessControlPage } from '../pages/AccessControlPage'
export { default as StorePage } from '../pages/StorePage'