export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS'
export const GET_WORKS_FAILED = 'GET_WORKS_FAILED'
export const GET_WORKS_LOADING = 'GET_WORKS_LOADING'
export const GET_WORKS = 'GET_WORKS'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_PROFILE = 'GET_PROFILE'
export const IS_LOG = 'IS_LOG'